version: '1.0.{build}-{branch}'
image: Ubuntu1804
services:
  - docker
cache:
  - 'nuget-package-dir'
  - 'docker-images'
  - 'v4-ref-assemblies'
  - 'dotnet-tools'
skip_commits:
  files:
    - '**/*.md'
    
environment:
  RELATIVE_NUGET_PACKAGE_DIR: 'nuget-package-dir/'
  RELATIVE_CS_OUTPUT: 'output/'
  CI_FOLDER: 'CIPipeline'
  DEPLOYABLE_BRANCH: 'HEAD'
  DOTNET_VERSION: '2.2'
  DEPLOY_NUGET_SOURCE: 'https://api.nuget.org/v3/index.json'
  ADDITIONAL_VOLUME_DIRECTORIES: 'v4-ref-assemblies'
  TEST_SCRIPT_WITHIN_CONTAINER: 'Build/test.sh'
  BUILD_SCRIPT_WITHIN_CONTAINER: 'Build/build.sh'
  DEPLOY_NUGET_NO_SYMBOLS: 'true'
  ASSEMBLY_SIGN_KEY:
    secure: uv6ZmcDLBG+//mfWJ1eugivE9k/q2hAss2p4cqD9u9l1br9SziHqcTAutv5+lt0TrX4cxARg6yYCPvSC3rsqstBlqAyWwpAXZ4vDW2ilHPF3m7VApB46RWNtX4jr1KbPSKWpOf0T+rdFgNinKOe+hc4+c9hk8jXHTUXHt3yfF2+MmBjgi+2Rt9LvSaOZDW17TWDlVQHFzYxFGWBc4EN9egSc3aX4j38GYayLQjFDLD5xraOl4PZqyW4MB86JeoWlGm6zmJXPDPhPtT/QAaD2W53dl5PO5T4qgOCEmr0ChnfP1L/z+drpMcFKFmPspThAklWpi5SaHSziNuzq4Ra/BV6HjIbGCLQ1742QBFAK+KSP/K7ulodwUYyOBQxj2uNlapNs2rBFRq8+o5CpbYmV/kOwpk6mTgL3Nzk0mqc7sJ1aMm07z0QqS1trcyK0qUPkFnFzlhUE5g3O0oaI2iGRVhftXxIbi87ikeFegGCohzAcLkYivCCR2IxLcTnI9HmGoNzSkZoGfwx6araNM5gXnN6EOTD4u/es0WfpGIEwcADSrS9xD+7l6TM95whvQ0BQ8QpnBnDNWCHMtNwCbyn4593WLzyKQTI9joYg2RkUR7eF5syFLOaYrNyz9X+vzK4ay6b20ODyTdbGhD7g9aXCIfjHRpsBNlafn2rA6ZysKnD9W9gJ99tLLSq6WhVSg/uJWFtghuV9gT6ZTkl9gxJhhszSrQ7+X9ekS7HPwJsvPCLYVDAVBJwZ9+cBNgDuYdTJa2Q/R+xkzZUsRXYXHrKKI0rK7Uxvd+Z53OWjo44gc7WAG49OlZFts5d5Anp7ecTY3ZWhI9twhn92rnSHd2By6uUUZI4x8lFy21O5UzzTQUx852BLgwneBbWlLjnkA18QzdM37a+eqghckRiYHbcWrOw+8wFMu55HDfIyGHBVHzUdJyEW7xq07eveLkS6NIXvhj0DN5ImVHeD+PPTB62vSci3WvSBS+z81fNp/XsyDN7+x1qC+FJ7rikKFFZv/SQHX9wYUimqp/MWY9C/m2z+NSPdvXgExKGgkiaYBi13wloUMgbbIRRU9RqxeyIgWQxtEEcOwZMa0ojHp3+9NvPIJjf45Z20G3O4WHGsRWWsRrqrAV/8WmlpP6piJz/AaX0jwmSG6ioqqIT+yWqNuTX0CAZB1a3TTBUtKXtWkQF32YEcBTsbXLlcs+0bqu2c8U/+m1aTW0VZ7zfc2VRphKTdrU9/eZs5B0bPK1H0vPlq96k4wVpxpF5ZRIpxT4BVsY4QE05VqAWoCz9BK8peksxwjMIzr5UZWFe78fT6EvZbuNPzsio8Uxt8m4G7Dmp/LrY3dvs3FX90s44S6MXFANZulMSl7s8fkFrLpmnKEXvOBNzNgrtU1674cQriUiWu+FS92UdGqoc77OAboURmymCQR3RyvA+YsqVyj0x3KyokblIbBgguXFgmhFU+RmIRg7g/jYKRpeAeb0E7O9NJk6wbE//DMjZWlKPXNLyOS4ffiQjMNWLgxuAny6U6coB8fAMJ/ONq0GWWZaN13/vgKJ4po7FWZY+c2gy8bhVlqc5mQ2oWm5I916mYHMtdUZgowzh/vy3lteEZHk/ze/c9XpzU4Gnf2aRPIB0yXf77Is7iNfbpu1zc+OaToYR6DQRjLsMJLjFpAKt1LdcRcW3PJ7ZMwAqL+f+jNp0nLoV4tg0ertc97PRb8OTGTK5s2rrR4yd31DMd0F79m9yoExUueu1ZwS2262B4/P2Lw02n6knJL5KE55AkLqm/z0/npMocDbus9ruf1vKvIoUioYa/Z/VaRFfmyoM0we4g7wCv6b/LPf0lj15W9wVfUH/Z03EyUA9uMg+AvVWWQ92UvupD12tKzNaVUn9jE6XulfScwCCNK6jTWQX+Uq4fVyQ7WB3IUqC5IR9BqbDPCsQHBVWnz3WG1BgFGu7coTgCjigjOZyIUNAcSeSVnvpmWBm+eVNcNsXLySh/w5v8rnD1LrCMEajodCI5imnNFg8ZoJuVvCRsGkkizUvVIm5eJoEpkVhRbDQG/4mpwV0nm04PSt933UcOOdtNJHGj0g/xPH9Kr1mglmdTmPqn96LBuP68kOnlLG684tMw4jSpcmiQo51xMTF9YUbio9tdp+8ToYWoXQ7FKH/EhmSrZW3Vp8O6yH2lAZXccyakDY7zcoGJ28r8J4SxzhGMquz9awvpmfG+KQJyf0mNRDNvvlDD1Kdy8+OXVZuCwjDg2U+U+LDXS0ZOgS04VN8bX4ARCVsTAxTa3RJM9+rnH1MNrJtmm24tA/8oRvAUp0r15mLcGtQFVZvpP0TVT1TSVtPwy1Ot9CUd5Mw54NRdNfgOn2lUDQy7N7Salc7h4glz4LkpVGDsRFz4aQDtsLpsnnCbxFP0cza+Qwsns+wiYOabQr/ql2iEFw4lRs20KurKCPA7TAca5OPfp0/ULxmhuW5fbA0qVeJLGE6wV+wmkUHFQ+2Q/iE9qk+RjlW/I4exXLtzaMIfPoMnLM36gGcFSAoadjsBuM+pGg6ZqGuKhsBTaE1CWlh5OACn34vnFoIC2qzZlUzz6vfjWNtgHE+afPODOO+FvXfgsQlSoZVoD288xYxFROJJI1vRF40RAqXR0I/89hxUEgcj+h1PN9PJCRzgBA5hQ8CTziYgSJLaOg1l6Ma9C6z7DLyt8wkQ+t1X1eWZhORe0XD3bSp6Wa0kGVcdJGyAGONBu4TqhmxZXgO8wRQbFPCWdE4PYE2ZxPfW4TvGEHxvo60bzwoFlB9B3Caaguem2UytuZOG3GuoQeiyxnI0/WxF+6bpqdhXxttEWr5hgZSvYQZFN3/n+E9Cpv7hJT0tpa8lPudNeeEm187WN+n/PqUIhhbF3GVIpvdFqhAknJlkFhSS98dzytPMnKKF4b/tC7ppVTjFF6bSl7AwaUcYKiQwZEjAxCHFBaI6m3J8hoF6emBrUywKaDACyR96yOqiYjnsPi2Qs6NLAcjLxhbdd+fu+sjhk/aRTf1ZcLEkqCX2VxktCaBZS4eAf4UIiRY5upbnkx/pRTSy7QyhzzzlYIFbzIIVFLC84SPVwh7V8DsTBeIa/RuNFOgNJcM2Yb1Y7uwL1CtJLL9nAIz6j5TiT70gkAzVfZ7me2n3GtyvHVMkcOr2mPWmvW++g+nA27ehNINwFiZDJM5e4LVtcOP/hv60P0VmGnj7vCTrgwbRg+5Ft5+JJ0ad0ByJC+yqebJqFm+Z6ltGJhKFmggedRiXeJ2FPmwRltJLsTLhy6OOmhdJ8pkapqD2Wp66A1eK5qIklEdpWQnOcM+lyefyxI0nEL6a/3dHUrEfNsNwz5/sZUcn4+uNxAccw3RA3W6gzNYsWZ0vuRT1Vv/fnRTnHK2W38gUisvy0WU6308FNQ5o/BBglZDsWMhsmI/mZ6ImN4m6wX/Y63EGCo3P2u19lAK521Zw2q5uH5mv6oMt4O45FXriBWTuDwMbnQY8BugX9C4+lsHyW8c7mYx1DhH2ZmpH4QU0t6/bYA9XPLQ62FMTdqQLSgnqvli3phkSBRdVQpcz1vP6RjKHCKggMFB2splZNgkTeq6u1UyOVH6L6IGJtONe5t4XDGJsdVRaKqX+iIZeVjdsw/L2xD3vNUNuzH6B20kz6PqgcCfU72P3907NUOpuMpnr2RiviOSzFWpvIUPVIF51Ba4v4c0sMgKih1HDxkLUrGnCnDA4KtDxPwyOhLwvP9f/4tn+9M5e1jUNSDwnZB3RZR9ZEFiLKwOZT57cX9rKJqyNIALpefzKELbx2/Y+Fxupt5Fem9GQw7NRv1A3tdgVlEp54aevsUkslUdhDEnbbja1GuxUDcRh5jOsgUHR6DhRokjmPCT8NgF1QdUVRo1eBc1NmIf21EXUsdIQyFYd6fftkYothc6FwiKvxbrfI+PlVpDiGqlUoCjaFfjOY2JVNVeuBCgJy7NZCrVFI1Yb9KPg1E2mFkLKfO6ijHR6QepCcqax1P3noxEeXRqIW6CMQn7Ea54LX9XMLBHrTpF173VDWTLd/++mzzn4sP2VMP3W7P1wzewqAVd6PO139/HTEt8xrVtSmkyw8cOCm+Q+b6KpvmVvAICYsujLwA8PLiW4FbzOs9heQluek2G9SvUQ1AAOZns=
  DEPLOY_NUGET_API_KEY:
    secure: BnABSE4ezwfebqsJWzZgRIXsca7FoHTcynHr2QrGbsgYUja5I5QZg4ePQUm+S4hV

  CODECOV_SSH_KEY:
    secure: 7FFY8hE4/u7joMUnEL8t36ujX2KG6veMNTDlIhFeSFW4F68GF7YkbVvWJ2iMiN1zxZQVDbZ+9hHDy3ALKLYGRVuHE7po+A63cFmHaUhbzTMVKu4VQGTh3457/quYuXbcVGnXZTbwFUZYtW4wEQb8VqDG40Yw642BqsU5c8ygIUdoVukc6JIg41nQcfLqdExbOMQ76Kx/NXRx1MsBRHd0dehFKzqYJ8PN0vRrdhPzPy1InrZVdwW+wUbcAHlPY3mOPK8o6GsqCRErWyukO1uD3hcGFEnNxOJbtZWhOk2qtt6rblN80RmYEtQFFzGw4uvO98qagJFJg/6GEwSlut5AiUZ2Tir8SrxKmVin345A4xN9rPHMckz3Z/T+/q+4a4DqiidheUYJWgc53V8UAzIi0Kr4ALrmfPzhQrSIb60WzvDhdb8N8wTTBkBfByD8wZvmHhp/0CNc4DANKVpytJcRjA==
  CODECOV_PAGES_USER_EMAIL:
    secure: sFI5KFdiAQM8HJHCF2uO517Kg+7rtEQ5yOWbnL/qOHBEJG73FOTguzovPJd6RuYg
  
init:
  - sh: git config --global core.autocrlf false
  - sh: appveyor UpdateBuild -Version "build-${APPVEYOR_REPO_COMMIT:0:8}-${APPVEYOR_BUILD_NUMBER}"

install:
  - sh: 'git -C "${APPVEYOR_BUILD_FOLDER}" submodule update --init --recursive'
  - sh: 'mkdir "${APPVEYOR_BUILD_FOLDER}/git"'
  - sh: 'git -C "${APPVEYOR_BUILD_FOLDER}" ls-tree --name-only -z HEAD | xargs --null mv -t "${APPVEYOR_BUILD_FOLDER}/git"'
  - sh: '"${APPVEYOR_BUILD_FOLDER}/git/${CI_FOLDER}/download-net40-ref-assemblies.sh" "${APPVEYOR_BUILD_FOLDER}/v4-ref-assemblies"'

before_build:
  - sh: '"${APPVEYOR_BUILD_FOLDER}/git/${CI_FOLDER}/appveyor/sync_docker_image.sh" "microsoft/dotnet:${DOTNET_VERSION}-sdk-alpine" "${APPVEYOR_BUILD_FOLDER}/docker-images/dotnet-sdk.tar"'

build_script:
  - sh: '"${APPVEYOR_BUILD_FOLDER}/git/${CI_FOLDER}/build.sh"'
  - sh: 'sudo chown -R `id -u` "${APPVEYOR_BUILD_FOLDER}/${RELATIVE_CS_OUTPUT}"'
  - sh: 'sudo chown -R `id -u` "${APPVEYOR_BUILD_FOLDER}/${RELATIVE_NUGET_PACKAGE_DIR}"'

test_script:
  - sh: '"${APPVEYOR_BUILD_FOLDER}/git/${CI_FOLDER}/test.sh" "${APPVEYOR_BUILD_FOLDER}/git/${CI_FOLDER}/appveyor/add_tests.sh"'
  - sh: 'sudo chown -R `id -u` "${APPVEYOR_BUILD_FOLDER}/${RELATIVE_CS_OUTPUT}"'
  - sh: 'sudo chown -R `id -u` "${APPVEYOR_BUILD_FOLDER}/${RELATIVE_NUGET_PACKAGE_DIR}"'

after_test:
  - sh: '"${APPVEYOR_BUILD_FOLDER}/git/${CI_FOLDER}/package.sh" "${APPVEYOR_BUILD_FOLDER}/git/${CI_FOLDER}/appveyor/upload_packages.sh"'
  - sh: 'sudo chown -R `id -u` "${APPVEYOR_BUILD_FOLDER}/${RELATIVE_CS_OUTPUT}"'
  - sh: 'sudo chown -R `id -u` "${APPVEYOR_BUILD_FOLDER}/${RELATIVE_NUGET_PACKAGE_DIR}"'
  
deploy_script:
  - sh: '${APPVEYOR_BUILD_FOLDER}/git/${CI_FOLDER}/deploy.sh'
